//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HumanResourceManagementDbContext : DbContext
    {
        public HumanResourceManagementDbContext()
            : base("name=HumanResourceManagementDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHUC_VU> CHUC_VU { get; set; }
        public virtual DbSet<CONG_SO> CONG_SO { get; set; }
        public virtual DbSet<DAN_TOC> DAN_TOC { get; set; }
        public virtual DbSet<DU_AN> DU_AN { get; set; }
        public virtual DbSet<KHEN_THUONG_NHAN_VIEN> KHEN_THUONG_NHAN_VIEN { get; set; }
        public virtual DbSet<KY_LUAT_NHAN_VIEN> KY_LUAT_NHAN_VIEN { get; set; }
        public virtual DbSet<LOAI_HOP_DONG> LOAI_HOP_DONG { get; set; }
        public virtual DbSet<LUONG> LUONGs { get; set; }
        public virtual DbSet<LUONG_NHAN_VIEN> LUONG_NHAN_VIEN { get; set; }
        public virtual DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
        public virtual DbSet<NHAN_VIEN_HOP_DONG> NHAN_VIEN_HOP_DONG { get; set; }
        public virtual DbSet<PHONG_BAN> PHONG_BAN { get; set; }
        public virtual DbSet<QUYEN> QUYENs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
        public virtual DbSet<TRINH_DO_HOC_VAN> TRINH_DO_HOC_VAN { get; set; }
    }
}
