//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUONG_NHAN_VIEN
    {
        public int id { get; set; }
        public Nullable<int> IdNhanVien { get; set; }
        public Nullable<int> ThangLuong { get; set; }
        public Nullable<int> NamLuong { get; set; }
        public Nullable<decimal> TienLuong { get; set; }
    }
}
