//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAN_VIEN_HOP_DONG
    {
        public int Id { get; set; }
        public Nullable<int> IdNhanVien { get; set; }
        public Nullable<int> IdLoaiHopDong { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
    
        public virtual LOAI_HOP_DONG LOAI_HOP_DONG { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
